
#define SAMPLES_PER_PACKET 8
#define HEADER_SIZE 5
#define TRAILER_SIZE 2
#define OVERHEAD_SIZE (HEADER_SIZE+TRAILER_SIZE)
#define SAMPLE_SIZE 4
#define SEQ_SIZE 4
#define TIMESTAMP_SIZE 8
//#define RR_SIZE 8
#define RR_SIZE 4
#define PAYLOAD_SIZE (RR_SIZE + SAMPLES_PER_PACKET*SAMPLE_SIZE + SEQ_SIZE + TIMESTAMP_SIZE)
#define PAYLOAD_SIZE_LSB (PAYLOAD_SIZE &0xFF)
#define PAYLOAD_SIZE_MSB ((PAYLOAD_SIZE >> 8) &0xFF)
#define PACKET_SIZE (PAYLOAD_SIZE + HEADER_SIZE + TRAILER_SIZE)

//#define PROTOCOL_VERSION 0x02
#define PROTOCOL_VERSION 0x03
#define PACKET_SOF1 0x0A
#define PACKET_SOF2 0xFA
#define PACKET_EOF 0x0b

